services:
  - type: web
    name: teacher-training-assessment
    env: node
    plan: standard
    buildCommand: npm install --legacy-peer-deps && NODE_OPTIONS="--max-old-space-size=4096" npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
