CREATE TABLE `teacher_portfolios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`isPublic` boolean NOT NULL DEFAULT false,
	`publicToken` varchar(64),
	`publicSlug` varchar(100),
	`bio` text,
	`specializations` json,
	`yearsOfExperience` int,
	`currentSchool` varchar(255),
	`region` varchar(100),
	`educationLevel` enum('primary','middle','secondary'),
	`totalLessonPlans` int NOT NULL DEFAULT 0,
	`totalExams` int NOT NULL DEFAULT 0,
	`totalImages` int NOT NULL DEFAULT 0,
	`totalCertificates` int NOT NULL DEFAULT 0,
	`totalEvaluations` int NOT NULL DEFAULT 0,
	`totalDigitizedDocs` int NOT NULL DEFAULT 0,
	`totalConversations` int NOT NULL DEFAULT 0,
	`subjectBreakdown` json,
	`lastPdfExportUrl` text,
	`lastPdfExportAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `teacher_portfolios_id` PRIMARY KEY(`id`),
	CONSTRAINT `teacher_portfolios_publicToken_unique` UNIQUE(`publicToken`),
	CONSTRAINT `teacher_portfolios_publicSlug_unique` UNIQUE(`publicSlug`)
);
