CREATE TABLE `video_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`batchId` int,
	`videoUrl` text,
	`videoDescription` text,
	`originalPrompt` text,
	`improvedPrompt` text,
	`scoreVisualQuality` int NOT NULL DEFAULT 0,
	`scoreNarrative` int NOT NULL DEFAULT 0,
	`scorePedagogical` int NOT NULL DEFAULT 0,
	`scoreEngagement` int NOT NULL DEFAULT 0,
	`scoreTechnical` int NOT NULL DEFAULT 0,
	`totalScore` int NOT NULL DEFAULT 0,
	`feedbackVisualQuality` text,
	`feedbackNarrative` text,
	`feedbackPedagogical` text,
	`feedbackEngagement` text,
	`feedbackTechnical` text,
	`overallFeedback` text,
	`attemptNumber` int NOT NULL DEFAULT 1,
	`toolUsed` varchar(100),
	`grade` varchar(50),
	`subject` varchar(100),
	`lessonTitle` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `video_evaluations_id` PRIMARY KEY(`id`)
);
