CREATE TABLE `page_configurations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`page_key` varchar(100) NOT NULL,
	`title_ar` varchar(255) NOT NULL,
	`title_fr` varchar(255),
	`title_en` varchar(255),
	`description_ar` text,
	`description_fr` text,
	`description_en` text,
	`path` varchar(255) NOT NULL,
	`icon` varchar(50),
	`parent_page` varchar(100),
	`is_visible` boolean NOT NULL DEFAULT true,
	`is_enabled` boolean NOT NULL DEFAULT true,
	`requires_auth` boolean NOT NULL DEFAULT false,
	`required_role` enum('user','admin') DEFAULT 'user',
	`required_tier` enum('free','pro','premium') DEFAULT 'free',
	`sort_order` int NOT NULL DEFAULT 0,
	`category` varchar(50),
	`badge_text` varchar(50),
	`badge_color` varchar(20),
	`page_type` enum('built_in','custom','external_link') NOT NULL DEFAULT 'built_in',
	`external_url` varchar(500),
	`custom_content` text,
	`meta_title` varchar(255),
	`meta_description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `page_configurations_id` PRIMARY KEY(`id`),
	CONSTRAINT `page_configurations_page_key_unique` UNIQUE(`page_key`)
);
