CREATE TABLE `generated_therapeutic_exercises` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`student_name` varchar(255),
	`student_age` int,
	`grade_level` varchar(50),
	`difficulty_type` varchar(100) NOT NULL,
	`exercise_category` varchar(100) NOT NULL,
	`difficulty_level` enum('beginner','intermediate','advanced') NOT NULL DEFAULT 'beginner',
	`subject` varchar(100),
	`specific_skill` varchar(255),
	`session_duration` int DEFAULT 20,
	`exercise_count` int DEFAULT 5,
	`title` varchar(500),
	`introduction` text,
	`exercises` json,
	`cooldown_activity` text,
	`teacher_notes` json,
	`parent_guidance` text,
	`status` enum('pending','completed','failed') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `generated_therapeutic_exercises_id` PRIMARY KEY(`id`)
);
