CREATE TABLE `follow_up_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`student_name` varchar(255) NOT NULL,
	`student_age` int,
	`grade_level` varchar(50),
	`school_name` varchar(255),
	`difficulty_type` varchar(100) NOT NULL,
	`severity_level` enum('mild','moderate','severe') NOT NULL DEFAULT 'moderate',
	`report_period` enum('weekly','monthly','trimesterly','yearly') NOT NULL DEFAULT 'monthly',
	`period_start_date` varchar(20),
	`period_end_date` varchar(20),
	`academic_observations` text,
	`behavioral_observations` text,
	`social_observations` text,
	`reading_score` int,
	`writing_score` int,
	`math_score` int,
	`attention_score` int,
	`social_score` int,
	`motivation_score` int,
	`historical_scores` json,
	`report_title` varchar(500),
	`executive_summary` text,
	`detailed_analysis` text,
	`strengths` json,
	`challenges` json,
	`recommendations` json,
	`parent_guidance` text,
	`next_steps` json,
	`status` enum('pending','completed','failed') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `follow_up_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `progress_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`student_name` varchar(255) NOT NULL,
	`student_age` int,
	`grade_level` varchar(50),
	`difficulty_type` varchar(100) NOT NULL,
	`evaluation_start_date` varchar(20) NOT NULL,
	`evaluation_end_date` varchar(20) NOT NULL,
	`assessment_data` json,
	`exercises_completed` json,
	`analysis_title` varchar(500),
	`overall_progress` enum('significant_improvement','moderate_improvement','slight_improvement','stable','slight_decline','needs_attention') NOT NULL DEFAULT 'stable',
	`progress_percentage` int,
	`detailed_analysis` text,
	`trend_analysis` text,
	`skills_improved` json,
	`skills_needing_work` json,
	`predictive_insights` text,
	`action_plan` json,
	`status` enum('pending','completed','failed') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `progress_evaluations_id` PRIMARY KEY(`id`)
);
