CREATE TABLE `reference_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`unite_number` int NOT NULL,
	`module_number` int NOT NULL,
	`journee_number` int NOT NULL,
	`niveau` varchar(50) NOT NULL DEFAULT '6ème année',
	`comm_orale_objet` text,
	`comm_orale_objectif` text,
	`comm_orale_remarques` text,
	`lecture_objet` text,
	`lecture_objectif` text,
	`lecture_remarques` text,
	`grammaire_type` enum('Grammaire','Conjugaison','Orthographe') NOT NULL DEFAULT 'Grammaire',
	`grammaire_objet` text,
	`grammaire_objectif` text,
	`grammaire_remarques` text,
	`is_official` boolean NOT NULL DEFAULT true,
	`source` varchar(255) DEFAULT 'Programme officiel tunisien',
	`notes` text,
	`added_by` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reference_content_id` PRIMARY KEY(`id`)
);
